### ISSUE TITLE
VARCHAR between 4000 and 8000 characters being truncated when build with UNICODE

### ISSUE THREAD

**Issue by LaurenceCarr** [w1nk/node-odbc#70]
I have a stored procedure with a VARCHAR(MAX). 

When called with a string of length < 4000 characters, or a string of > 8000 characters it works.
When called with a string of length between 4000 and 8000 the string is truncated to 4000 characters.

If I re-build with UNICODE turned off it works as expected similarly if I make this change it works:

```
       params[i].c_type        = SQL_C_TCHAR;
 #ifdef UNICODE
-      params[i].type          = (length >= 8000) ? SQL_WLONGVARCHAR : SQL_WVARCHAR;
+      params[i].type          = (length >= 4000) ? SQL_WLONGVARCHAR : SQL_WVARCHAR;
       params[i].buffer_length = (length * sizeof(uint16_t)) + sizeof(uint16_t);
 #else
       params[i].type          = (length >= 8000) ? SQL_LONGVARCHAR : SQL_VARCHAR;
```

Is this is node-odbc bug?

**Comment by wankdanker** [comment]
It is most likely a node-odbc bug. What database/driver are you using this with?

I updated the long string test to test for the conditions you mentioned and can see that this is an issue with at least FreeTDS and the MSSQL Native CLI driver. Although, the failure is actually different than you describe here.

I actually don't like the length check in general because I'm not positive, but my guess is that the 4000 or 8000 number may vary per database. And since this is ODBC it should be pretty database agnostic.

Back to the test, without any modifications at all, Sqlite3 and MySQL pass. If I remove the length check and always specify SQL_WLONGVARCHAR when Unicode is enabled and always specify SQL_LONGVARCHAR when Unicode is disabled, then Sqlite3, MySQL and MSSQL Native CLI pass.

**Comment by wankdanker** [comment]
I realize now that the FreeTDS failure was because the default max length for a string is 2048. I had to change that in my connection string in order for the tests to work properly. With the corrected connection string FreeTDS and MSSQLNCLI were still failing. But everything now works with ffee158; always use SQL_WLONGVARCHAR or SQL_LONGVARCHAR.

If you can install with `npm install https://github.com/wankdanker/node-odbc/tarball/v0.6` and see if it works for you, that would be great. If it does work, I'll release a new version to npm.

Thanks,

Dan

**Comment by wankdanker** [comment]
I released v0.6.11 which should fix this issue. Please let me know if you are all set so we can close this issue.

Thanks,

Dan

**Comment by LaurenceCarr** [comment]
Thanks - I neglected to mention in the original report that I was using FreeTDS (version 7.2) and MSSQL 2012. 

Tested it and it works! Thanks.

**Comment by wankdanker** [comment]
Great. Glad to hear. Thank you for following up.
