### ISSUE TITLE
-1 returns as UINT_MAX

### ISSUE THREAD

**Issue by DaveTCode** [w1nk/node-odbc#85]
I'm running node-odbc talking to a MSSQL server on 2008R2 using FreeTDS version 7.2

When I get a value of -1 back in a result set it is mapping to 4 294 967 295. Coincidentally (not) that is UINT_MAX as per https://msdn.microsoft.com/en-gb/library/296az74e.aspx.

The SQL field is a simple int field so why is it being converted to a uint here? I can't see anything odd looking in odbc.cpp so I'm guessing this is a FreeTDS issue.

**Comment by wankdanker** [comment]
This is definitely something in node-odbc. I'm going to try to track down the version in which it showed up.

**Comment by wankdanker** [comment]
This is fixed in 53d4a235 which was released to npm in v1.1.6. Give that version a shot and see if fixes your issue while not creating others. :)

This was happening on Sqlite, FreeTDS and the MSSQL Native Linux driver. But it was not happening on MySQL. I think the issue had to do with passing a `long value` to `NanNew<Number>(value)`. I changed it to `int32_t value` and `NanNew<Integer>(value)`. 

I think we tried this before but Nan wouldn't allow returning that Integer type. That appears to be fixed now. 

Please let me know if this works out for you so we can close the issue.

**Comment by DaveTCode** [comment]
Sorry it took so long, I've managed to retest this now and can confirm it's working (at least in my very specific case).

Thanks for the help!

Closed
