### ISSUE TITLE
Large XML parameters are being interpreted as NVARCHAR(4000) 

### ISSUE THREAD

**Issue by jbaxter0810** [w1nk/node-odbc#96]
I'm currently using the node-odbc to connect to our SQL Server database. It's a pretty standard connection. I pass in the query and an array of parameters (params). The problem is when I have rather large amounts of text within a parameter. Over 4000 characters.

```
db.open(cn, function (err) {
    if (err) {
        console.log(req.fullPath);
        console.log(JSON.stringify({'Error': err.toString() }));
        res.writeHead(500, 'Internal Server Error', {'content-type': 'application/vnd.collection+json'});
        res.end(JSON.stringify({Error: req.SystemErrors.GetError(req.SystemErrors.ErrorConnectingToDatabase)}));
        return;
    }

    db.query(query, params, function (err, data) {
        if (err) {
            res.writeHead(500, 'Internal Server Error', {'content-type': 'application/vnd.collection+json'});
            res.end(JSON.stringify({Error: req.SystemErrors.GetError(req.SystemErrors.ErrorRunningQuery)}));
            return;
        } else if (typeof data[0] === 'undefined') {
            res.writeHead(200, 'OK', {'content-type': 'application/vnd.collection+json'});
            res.end(JSON.stringify({ 'Message': 'No data returned for this request.' }));
            return;
        } else {
            next(data);
        }

        db.close(function (err) {
            if (err) {
                res.writeHead(500, 'Internal Server Error', {'content-type': 'application/vnd.collection+json'});
                res.end(JSON.stringify({Error: req.SystemErrors.GetError(req.SystemErrors.ErrorClosingDatabaseConnection)}));
            }
        });
    });
});
```

I ran into this issue when trying to pass over a large XML variable type to my stored procedure in MS SQL Server. I did a trace on the data being passed over and node-odbc interpreted this XML as an NVARCHAR(4000), thus truncating the value stored in this variable.

So my question is, how can I tell node-odbc the variable type (XML, VARCHAR(MAX), ect) OR set the length of of the variable?

Thanks!

**Comment by bzuillsmith** [comment]
Hmmm we occasionally have issues with this. The way the code is now, we assume the driver will figure out the proper type. What odbc driver are you using?

Not all odbc drivers handle strings in the same way, so we may have to add some configuration for this, or we'll have to hard-code behavior for the drivers that have issues with the current implementation. Unfortunately, there is no workaround at the moment. 

If you're feeling brave, you can fork node-odbc and correct the problem for your driver. The code to modify is [here](https://github.com/wankdanker/node-odbc/blob/master/src/odbc.cpp#L684-L698)

 I have an example of this for an old MSAccess datasource [here](https://github.com/bzuillsmith/node-odbc/blob/msaccess-bind/src/odbc.cpp#L684-L704). Instead of the 255 limit, you can put 4000 I think.

**Comment by jbaxter0810** [comment]
Thanks, I'm looking into this more now. I'm using the FreeTDS driver version 7.2

**Comment by jbaxter0810** [comment]
Thanks for the help @bzuillsmith. I updated and tested the code to handle this. I sent a pull request to the wankdanker/node-odbc branch.
